language: node_js

node_js:
- 8.12.0

script:
- npm run lint && npm test

# Update files which need the right version number, build the packed
# release, install the nfpm tool and build the release deb package.
before_deploy:
- version=${TRAVIS_TAG/v/}
- npm version --no-git-tag-version ${version}
- npm run release
- "curl -sL https://github.com/goreleaser/nfpm/releases/download/v0.9.5/nfpm_0.9.5_Linux_x86_64.tar.gz | tar -C /tmp -xzf -"
- /tmp/nfpm pkg -t cacophony-web-vuex_${version}.deb

deploy:
  provider: releases
  api_key:
    secure: A7tIX+Qeu5edDUT5tQnA0KvnDdrFeZ0quLkswUexLhuCLa29UfanQEzTsEvHlBY1VARYJ8PlzHWpMzZHuc9wWkI73dNyTqSU/mr7yJ1nvlXqrPIjZORLy+QOmUhI8StbmTw9IGR7ljHKF8DUBqY4aQoeGCBYAv9OIPiM2yZ2RjCyfteYxE1QVlzBgEzyR060i5wI1sFfy8dc8w5x8eg4KOlsypLOAcQb4T21sFrGvnGi+7CrfmrZNcbjPiL1Iiz+i0zuP/9DFeWzYnI+R9+rNGAEDv3SMCTtH5gcOdlbuPOiNPY7m+Lazyhj43QG6CEpcmUrb8yXHL7mWkjArxYbkHiAc2KkFmcjmutUQIapGzBeSGSWGWHY9r/7EleJ0Ht+ujWCczXXV/mpte4K8q4NaiUnzQZ+YWU0LFpoH4mEKymt/nFRkXNHe9ARxjDInKWO9YpQ7IYlB9rmh9gnLwMc92blV7lAvWvAiTtTjHKVdUdb0Gdlpr7rf+YOcASB+OqJsjeK0pqX09qQ3QACOcq0A21GlDGHhJ0PjIz0Pq1ss9xLf775tjyprHfDQCthN9GW0qXLw75zSHia0RoVuFQWLCHYBZoszoCNnfT3MN2CofMAPahMrbdo7ad+aJMZr8jD/wzPaaNfMJ5Vm8Cg9DTHgKStaRktR8laUO9KYnlcQlI=
  file_glob: true
  file: "*.deb"
  on:
    tags: true
    repo: TheCacophonyProject/cacophony-web-vuex
