language: node_js
node_js:
- 8.12.0

script:
- npm run lint && npm test

# Update files which need the right version number, build the packed
# release, install the nfpm tool and build the release deb package.
before_deploy:
- version=${TRAVIS_TAG/v/}
- npm version --no-git-tag-version ${version}
- npm run release
- "curl -sL https://github.com/goreleaser/nfpm/releases/download/v0.9.5/nfpm_0.9.5_Linux_x86_64.tar.gz | tar -C /tmp -xzf -"
- /tmp/nfpm pkg -t cacophony-web-vuex_${version}.deb

deploy:
  provider: releases
  api_key:
    secure: aER3hb7RVpQjmEZOcXoRIOgq/XI+G0jlhOGhDzHAR+TkUdrfSFcO9frc3865itf4cScDhFN1KlTY4P58mKGlUFgIgq962mlUTsEZPifOblplFTDYMcCGR1ZEATx1qLKGf/VAaCKqfV9s4B8H9+a2/cMb/pIzQs5L0nFrEyR3Exg/NyH/BkVdYnIECWT4boQecgZcpaXYehIMSg1TJOOKYLpUMqv79gZ30L6BI0gHkov2wX19E1GWsJ2K5NVklQpoDS/I7cxyGSNnX2QX3uZCKvEfDoiWFjDsNIVs5lMA9bXem+BzBa/q043VOfJH9RPqOOl0ujr8drOLmW+ej3raMfCiBX+DMy0WCvENeVxzfeveVnF0yN8hVV+ViTCqH2wOnmw6AOp/4v5EYD9guAV45QEVnvhfaqyQtgym9VeZxiktkeOo4Eu5soZxkXBdoiTWVX00Sq3/jwn1mlFNO1dTQ4nPZcMdNHUI5tseUD1W1xd1fVyUWhl9LkQStwN867YhBwZdK5k6w/Cv/QE706RkUI2KLD3du7580YO2Qxgui5HId8itdd60Izw7UZs65pE7WxEIOifSfvqf7/r47PCQIzfD0cdSg808HWTka+4ISjgOOo9goF7zDH1CJtm5dB51INxby0S1zprCLsL5s42tqt+uTvEurUuRE/kJBp3DM7M=
  skip_cleanup: true
  file_glob: true
  file: "*.deb"
  on:
    tags: true
    repo: TheCacophonyProject/cacophony-web-vuex
