language: node_js

node_js:
- 8.12.0

script:
- npm run lint && npm test

# Update files which need the right version number, build the packed
# release, install the nfpm tool and build the release deb package.
before_deploy:
- version=${TRAVIS_TAG/v/}
- npm version --no-git-tag-version ${version}
- npm run release
- "curl -sL https://github.com/goreleaser/nfpm/releases/download/v0.9.5/nfpm_0.9.5_Linux_x86_64.tar.gz | tar -C /tmp -xzf -"
- /tmp/nfpm pkg -t cacophony-web-vuex_${version}.deb

deploy:
  provider: releases
  api_key:
    secure: UGwpeFU4DE+Etvhls31v8Wrjs2WhihQWXtL5I3l1y2NAtxELAU1/5UpeYBVXsfibK96XZUaMMDDptKeAWJzCLJRISEhC1fxGhvew0l6DU4gl9duw8rSET/jP/kkTAb/TNVt2rjmzYKANleKkloZBr+bOi76UF15rXtX9YC9eeBTcu9nWtSKzlBU1T/FPymdXdX5LxfKpFUFWS1mnhxYXsJ97oL2pHVKtGkXfuUpys/ckbGTcOCyHQaJzxyRK7WJ9C3HIpVAcDK/bHI1lQNCgwF2K3MvBMHa7MCmcWvfEPQYv2P3w+FFiVN5C/DUe6Mj+dk2L67xAEdT+IzZA4gb+CrSPHG5NDrCdflDtEWll0ko4+/D66UfJojklytyTowSozCZOqA0kdxtciRfYg9eGW1HFD5ZZJAx1yxLQ2RaUxzAhoBW+OunRGzHPXDXehXnB1Pj6AV8oTrY9M7GBH28zVs6w+pas11VqJkAaeucf1JQo8uBJtPp5VEt0AtrTH/SaMYkvkMU/b8jR8KP7BoRHtmJMDWQuJO0UuWZZxjGvwncPMIX92OhNzRz1mXoHBD/xjA8WIeL3r3ovMVLCQXHg51YbDABoGstLwdXRwirjVC0aEqYe+5xLPnvPOLJXu9+IZ4J4pjXc6prQY6S+MpigHguHQNKrnnGwOqw3mMSx2LM=
  file_glob: true
  file: "*.deb"
  on:
    tags: true
